### ISSUE TITLE
Формулировка пункта 1.2.1 неверна

### ISSUE THREAD

**Issue by ramm** [tochka-public/Holacracy-Constitution-RUSSIAN#1]
> Выполняющий Роль обязан отслеживать как описана Миссия и Обязательства его Роли, соотносить существующее описание со своим видением возможного идеального описания, определять несоответствия между реальностью и собственным представлением об идеале (каждое такое несоответствие и есть «Напряжение»). Выполняющий Роль также должен пытаться разрешить эти Напряжения, используя доступные ему полномочия и другие способы воздействия, описанные в данной Конституции. 

Это не верно, "express" это не про описание, а про то, как у выполняющего роль получается её делать. Т.е. "вот так получается, а вот так должно быть — разница это Tension, который надо попробовать сгладить и двинуться к идеалу".

Английский исходник: http://www.holacracy.org/constitution#art121

**Comment by ramm** [comment]
Я пока исправлю на 

> Выполняющий Роль обязан отслеживать как выполняются Миссия и Обязательства его Роли, соотносить существующее выполнение со своим видением возможного идеального выполнения, определять несоответствия между реальностью и собственным представлением об идеале (каждое такое несоответствие и есть **_«Напряжение»_**). Выполняющий Роль также должен пытаться разрешить эти Напряжения, используя доступные ему полномочия и другие способы воздействия, описанные в данной Конституции.

Но по-моему это очень корявая и громоздкая конструкция, надо её поправить

**Comment by eveva** [comment]
Выполняющий Роль обязан отслеживать как исполняются Миссия и Обязательства его Роли, соотносить и определять несоответствия между реальным состоянием и собственным представлением об идеале (каждое такое несоответствие и есть «Напряжение»). Выполняющий Роль должен пытаться разрешить эти Напряжения, используя доступные ему полномочия и другие способы, описанные в данной Конституции.

**Comment by eveva** [comment]
пока так) можно сделать еще заход на упрощение

**Comment by ramm** [comment]
Мне видится проблемой то, что фраза "соотносить и определять несоответствия между реальным состоянием и собственным представлением об идеале" никак не говорит, что это про работу, а не про красивый дизайн структуры.

**Comment by eveva** [comment]
Выполняющий Роль обязан отслеживать как исполняются Миссия и Обязательства его Роли, соотносить и определять несоответствия между реальным результатом и собственным представлением об идеальном (каждое такое несоответствие и есть «Напряжение»). Выполняющий Роль должен пытаться разрешить эти Напряжения, используя доступные ему полномочия и другие способы, описанные в данной Конституции.
