### ISSUE TITLE
Linked Entity

### ISSUE THREAD

**Issue by ramm** [tochka-public/Holacracy-Constitution-RUSSIAN#4]
- Связанная Группа (сейчас так)
- Связанная Сущность (дословно, криво звучит)
- ... ?

**Comment by ramm** [comment]
Особенно тяжело это воспринимается в 2.7.5

**Comment by eveva** [comment]
у меня ассоциация перевода бы ушла в аналогию с legal entity, ну типа какое-то лицо /представитель(и), "связанная группа" непонятно звучит

**Comment by ramm** [comment]
ну да. вопрос в том, что по тексту это самое linked entity — это и круг, и какая-то внешняя сущность типа сторонней компании или совета директоров.

**Comment by eveva** [comment]
главное передать смысл - "запрошенные представители",  согласен?

**Comment by ramm** [comment]
"представители" это как раз Кросс-линки. а linked entity это то, откуда эти представители пришли. :)

**Comment by ramm** [comment]
В общем, будет Группа
