### ISSUE TITLE
управляющие лица Организации — ratifiers

### ISSUE THREAD

**Issue by ramm** [tochka-public/Holacracy-Constitution-RUSSIAN#5]
Смущает меня эта формулировка.

Но "Ратификаторы" — ещё хуже.

**Comment by eveva** [comment]
здесь же про тех, кто подписал конституцию, может так и писать?

**Comment by ramm** [comment]
"лица, подписавшие конституцию"?

**Comment by ramm** [comment]
они не конституцию подписывают, а документ о ратификации

**Comment by eveva** [comment]
Принявшие конституцию, харе буквоедствовать.
